version: '3'
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.devsecure.address=:8443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.filename=/etc/traefik/rules.yml"

    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./rules.yml:/etc/traefik/rules.yml"
  redis-server:
    image: redis
    ports: 
      - "6379:6379"
  
  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: app
    ports:
      - 5000
    environment:
      - VITE_SITE_TITLE
      - VITE_SITE_HOST
      - VITE_SITE_CONTACT
      - REDIS_PREFIX
    volumes:
      - "../dist:/opt/app/dist"
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.http.routers.app.rule=Host(`hmdev.mshome.net`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      
  
